version: '3'
services:
  shipping:
    build: .
    container_name: "shipping-service"
    ports:
      - "8080:8080"
    environment:
      SC_HOST: "servicecenter:30100"
    links:
      - servicecenter:servicecenter
  servicecenter:
    image: servicecomb/service-center
    ports:
      - "30100:30100"

